const CHANGE_PAGE_NO = "CHANGE_PAGE_NO";

const GET_LIKE_LIST_REQUEST = "GET_LIKE_LIST_REQUEST";
const GET_LIKE_LIST_SUCCESS = "GET_LIKE_LIST_SUCCESS";
const GET_LIKE_LIST_FAILURE = "GET_LIKE_LIST_FAILURE";

const CLEAR_LIKE_LIST_RESPONSE ="CLEAR_LIKE_LIST_RESPONSE"

export{CHANGE_PAGE_NO ,GET_LIKE_LIST_REQUEST,GET_LIKE_LIST_SUCCESS,GET_LIKE_LIST_FAILURE,
    CLEAR_LIKE_LIST_RESPONSE}