const CHANGE_MESSAGE_DETAIL = "CHANGE_INPUT_MESSAGE"

const CLEAR_MESSAGE_DETAIL = "CLEAR_MESSAGE_DETAIL";

const CHANGE_FRDS_ACKNOWLEDGE = "CHANGE_FRDS_ACKNOWLEDGE"

const CHANGE_SOCKET_ID ="CHANGE_SOCKET_ID"

const COMPLETE_MESSAGE_LIST = "COMPLETE_MESSAGE_LIST";

const CHECK_IS_ONLINE ="CHECK_IS_ONLINE"

const CHANGE_BLOCKED_STATUS = "CHANGE_BLOCKED_STATUS"

export {CHANGE_MESSAGE_DETAIL ,CHANGE_FRDS_ACKNOWLEDGE ,CHANGE_SOCKET_ID ,COMPLETE_MESSAGE_LIST ,
    CLEAR_MESSAGE_DETAIL ,CHECK_IS_ONLINE ,CHANGE_BLOCKED_STATUS }