const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
const CHAT_LIST_FAILURE = "CHAT_LIST_FAILURE";

const CHANGE_CHAT_PAGE_NO = "CHANGE_CHAT_PAGE_NO";

const CLEAR_CHAT_LIST_RESPONSE = "CLEAR_CHAT_LIST_RESPONSE"

const CHANGE_CHAT_LIST = "CHANGE_CHAT_LIST";

const CHANGE_CHAT_COUNT = "CHANGE_CHAT_COUNT";

const COUNT_CHAT_LIST_CLICK = "COUNT_CHAT_LIST_CLICK"

export { CHAT_LIST_REQUEST, CHAT_LIST_SUCCESS, CHAT_LIST_FAILURE, CHANGE_CHAT_PAGE_NO, CLEAR_CHAT_LIST_RESPONSE, 
    CHANGE_CHAT_LIST ,CHANGE_CHAT_COUNT ,COUNT_CHAT_LIST_CLICK }