const SINGLE_PROFILE_DATA_REQUEST = "SINGLE_PROFILE_DATA_REQUEST";
const SINGLE_PROFILE_DATA_SUCCESS = "SINGLE_PROFILE_DATA_SUCCESS";
const SINGLE_PROFILE_DATA_FAILURE = "SINGLE_PROFILE_DATA_FAILURE";

const CLEAR_SINGLE_PROFILE_DATA = "CLEAR_SINGLE_PROFILE_DATA";

const ADD_REMOVE_FAVORITE_DATA_REQUEST = "ADD_REMOVE_FAVORITE_DATA_REQUEST";
const ADD_REMOVE_FAVORITE_DATA_SUCCESS = "ADD_REMOVE_FAVORITE_DATA_SUCCESS";
const ADD_REMOVE_FAVORITE_DATA_FAILURE = "ADD_REMOVE_FAVORITE_DATA_FAILURE";

const CLEAR_ADD_REMOVE_DATA = "CLEAR_ADD_REMOVE_DATA";

const CHANGE_REPORT_USER_INPUT = "CHANGE_REPORT_USER_INPUT";

const REPORT_USER_API_REQUEST = "REPORT_USER_API_REQUEST";
const REPORT_USER_API_SUCCESS = "REPORT_USER_API_SUCCESS";
const REPORT_USER_API_FAILURE = "REPORT_USER_API_FAILURE";

const CLEAR_REPORT_USER_RESPONSE = "CLEAR_REPORT_USER_RESPONSE";

const REPORT_LIST_API_REQUEST = "REPORT_LIST_API_REQUEST";
const REPORT_LIST_API_SUCCESS = "REPORT_LIST_API_SUCCESS";
const REPORT_LIST_API_FAILURE = "REPORT_LIST_API_FAILURE";

const PUR_USER_API_REQUEST = "PUR_USER_API_REQUEST";
const PUR_USER_API_SUCCESS = "PUR_USER_API_SUCCESS";
const PUR_USER_API_FAILURE = "PUR_USER_API_FAILURE";

const CLEAR_PURR_USER_RESPONSE = "CLEAR_PURR_USER_RESPONSE";

const BLOCK_UNBLOCK_API_REQUEST = "BLOCK_UNBLOCK_API_REQUEST";
const BLOCK_UNBLOCK_API_SUCCESS = "BLOCK_UNBLOCK_API_SUCCESS";
const BLOCK_UNBLOCK_API_FAILURE = "BLOCK_UNBLOCK_API_FAILURE";

const CLEAR_BLOCK_UNBLOCK_RESPONSE = "CLEAR_BLOCK_UNBLOCK_RESPONSE"

const CHECK_MESSAGE_LIMIT_REQUEST = "CHECK_MESSAGE_LIMIT_REQUEST";
const CHECK_MESSAGE_LIMIT_SUCCESS = "CHECK_MESSAGE_LIMIT_SUCCESS";
const CHECK_MESSAGE_LIMIT_FAILURE = "CHECK_MESSAGE_LIMIT_FAILURE";

const CLEAR_MESSAGE_LIMIT_RESPONSE = "CLEAR_MESSAGE_LIMIT_RESPONSE";

const CLEAR_LIKES_LIMIT_REACH = "CLEAR_LIKES_LIMIT_REACH"
export {
    SINGLE_PROFILE_DATA_REQUEST, SINGLE_PROFILE_DATA_SUCCESS, SINGLE_PROFILE_DATA_FAILURE, CLEAR_SINGLE_PROFILE_DATA,
    ADD_REMOVE_FAVORITE_DATA_REQUEST, ADD_REMOVE_FAVORITE_DATA_SUCCESS, ADD_REMOVE_FAVORITE_DATA_FAILURE, CLEAR_ADD_REMOVE_DATA,
    REPORT_USER_API_REQUEST, REPORT_USER_API_SUCCESS, REPORT_USER_API_FAILURE, REPORT_LIST_API_REQUEST, REPORT_LIST_API_SUCCESS,
    REPORT_LIST_API_FAILURE, PUR_USER_API_REQUEST, PUR_USER_API_SUCCESS, PUR_USER_API_FAILURE, CLEAR_REPORT_USER_RESPONSE,
    CHANGE_REPORT_USER_INPUT, CLEAR_PURR_USER_RESPONSE, BLOCK_UNBLOCK_API_REQUEST, BLOCK_UNBLOCK_API_SUCCESS, BLOCK_UNBLOCK_API_FAILURE,
    CLEAR_BLOCK_UNBLOCK_RESPONSE,CHECK_MESSAGE_LIMIT_REQUEST,CHECK_MESSAGE_LIMIT_SUCCESS,CHECK_MESSAGE_LIMIT_FAILURE,
    CLEAR_MESSAGE_LIMIT_RESPONSE ,CLEAR_LIKES_LIMIT_REACH
}