const CHANGE_UPDATE_PROFILE_INPUT ="CHANGE_UPDATE_PROFILE_INPUT";

const UPDATE_PROFILE_DATA_REQUEST = "UPDATE_PROFILE_DATA_REQUEST";
const UPDATE_PROFILE_DATA_SUCCESS = "UPDATE_PROFILE_DATA_SUCCESS";
const UPDATE_PROFILE_DATA_FAILURE = "UPDATE_PROFILE_DATA_FAILURE";

const CLEAR_UPDATE_PROFILE_RESPONSE ="CLEAR_UPDATE_PROFILE_RESPONSE";

const GET_PLAN_DETAIL_API_REQUEST = "GET_PLAN_DETAIL_API_REQUEST";
const GET_PLAN_DETAIL_API_SUCCESS = "GET_PLAN_DETAIL_API_SUCCESS";
const GET_PLAN_DETAIL_API_FAILURE = "GET_PLAN_DETAIL_API_FAILURE";

const CLEAR_PLAN_DETAIL_RESPONSE ="CLEAR_PLAN_DETAIL_RESPONSE"

const LOGOUT_API_REQUEST = "LOGOUT_API_REQUEST";
const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
const LOGOUT_API_FAILURE = "LOGOUT_API_FAILURE";

const DEACTIVATE_ACTIVATE_API_REQUEST = "DEACTIVATE_ACTIVATE_API_REQUEST";
const DEACTIVATE_ACTIVATE_API_SUCCESS = "DEACTIVATE_ACTIVATE_API_SUCCESS";
const DEACTIVATE_ACTIVATE_API_FAILURE = "DEACTIVATE_ACTIVATE_API_FAILURE";

const CLEAR_DEACTIVATE_ACTIVATE_RESPONSE = "CLEAR_DEACTIVATE_ACTIVATE_RESPONSE";

const CLEAR_LOGOUT_RESPONSE ="CLEAR_LOGOUT_RESPONSE"

const CHANGE_ACTIVATE_DEACTIVATE_INPUT ="CHANGE_ACTIVATE_DEACTIVATE_INPUT";

const RAZORPAY_PAYMENT_API_REQUEST = "RAZORPAY_PAYMENT_API_REQUEST";
const RAZORPAY_PAYMENT_API_SUCCESS = "RAZORPAY_PAYMENT_API_SUCCESS";
const RAZORPAY_PAYMENT_API_FAILURE = "RAZORPAY_PAYMENT_API_FAILURE";

const CLEAR_RAZORPAY_PAYMENT_RESPONSE = "CLEAR_RAZORPAY_PAYMENT_RESPONSE";

const CHANGE_RAZORPAY_PAYMENT_DETAIL ="CHANGE_RAZORPAY_PAYMENT_DETAIL"

const STORE_RAZORPAY_PAYMENT_API_REQUEST = "STORE_RAZORPAY_PAYMENT_API_REQUEST";
const STORE_RAZORPAY_PAYMENT_API_SUCCESS = "STORE_RAZORPAY_PAYMENT_API_SUCCESS";
const STORE_RAZORPAY_PAYMENT_API_FAILURE = "STORE_RAZORPAY_PAYMENT_API_FAILURE";

const CLEAR_STORE_RAZORPAY_PAYMENT_RESPONSE ="CLEAR_STORE_RAZORPAY_PAYMENT_RESPONSE"

export{CHANGE_UPDATE_PROFILE_INPUT ,UPDATE_PROFILE_DATA_REQUEST,UPDATE_PROFILE_DATA_SUCCESS,UPDATE_PROFILE_DATA_FAILURE,
    CLEAR_UPDATE_PROFILE_RESPONSE,GET_PLAN_DETAIL_API_REQUEST,GET_PLAN_DETAIL_API_SUCCESS,GET_PLAN_DETAIL_API_FAILURE,
    CLEAR_PLAN_DETAIL_RESPONSE ,LOGOUT_API_REQUEST ,LOGOUT_API_SUCCESS ,LOGOUT_API_FAILURE ,CLEAR_LOGOUT_RESPONSE,
    CHANGE_ACTIVATE_DEACTIVATE_INPUT ,DEACTIVATE_ACTIVATE_API_REQUEST , DEACTIVATE_ACTIVATE_API_SUCCESS,DEACTIVATE_ACTIVATE_API_FAILURE,
    CLEAR_DEACTIVATE_ACTIVATE_RESPONSE ,RAZORPAY_PAYMENT_API_REQUEST,RAZORPAY_PAYMENT_API_SUCCESS,RAZORPAY_PAYMENT_API_FAILURE,
    CHANGE_RAZORPAY_PAYMENT_DETAIL ,CLEAR_RAZORPAY_PAYMENT_RESPONSE,STORE_RAZORPAY_PAYMENT_API_REQUEST,STORE_RAZORPAY_PAYMENT_API_SUCCESS,
    STORE_RAZORPAY_PAYMENT_API_FAILURE,CLEAR_STORE_RAZORPAY_PAYMENT_RESPONSE
}