const CHANGE_FILTER_INPUT = "CHANGE_FILTER_INPUT"

const GET_FILTER_DATA_REQUEST = "GET_FILTER_DATA_REQUEST";
const GET_FILTER_DATA_SUCCESS = "GET_FILTER_DATA_SUCCESS";
const GET_FILTER_DATA_FAILURE = "GET_FILTER_DATA_FAILURE";

const CLEAR_FILTER_LIST_AFTER_CALL_RESPONSE = "CLEAR_FILTER_LIST_AFTER_CALL_RESPONSE";

const CLEAR_FILTER_LIST_RESPONSE ="CLEAR_FILTER_LIST_RESPONSE"

const CLEAR_FILTER_INPUT = "CLEAR_FILTER_INPUT";

const CHANGE_FILTER_LIST ="CHANGE_FILTER_LIST";

export {CLEAR_FILTER_LIST_AFTER_CALL_RESPONSE, CHANGE_FILTER_INPUT ,GET_FILTER_DATA_REQUEST ,GET_FILTER_DATA_SUCCESS ,GET_FILTER_DATA_FAILURE ,
    CLEAR_FILTER_INPUT ,CLEAR_FILTER_LIST_RESPONSE ,CHANGE_FILTER_LIST}