const MAIN_STEP_INPUT_CHANGE = "MAIN_STEP_INPUT_CHANGE";

const VERIFY_CODE_INPUT = "VERIFY_CODE_INPUT";

const ABOUT_INFO_INPUT = "ABOUT_INFO_INPUT";

const ACCOUNT_INFO_INPUT = "ACCOUNT_INFO_INPUT";

const CHANGE_LOGIN_STEP = "CHANGE_LOGIN_STEP";

const CHANGE_UPLOADIMAGE_INPUT = "CHANGE_UPLOADIMAGE_INPUT"

const CHOOSE_LOCATION_INPUT = "CHOOSE_LOCATION_INPUT"

const CHANGE_LOOKINGFOR_INPUT = "CHANGE_LOOKINGFOR_INPUT"

const GET_RELATIONSHIP_DATA_REQUEST = "GET_RELATIONSHIP_DATA_REQUEST";
const GET_RELATIONSHIP_DATA_SUCCESS = "GET_RELATIONSHIP_DATA_SUCCESS";
const GET_RELATIONSHIP_DATA_FAILURE = "GET_RELATIONSHIP_DATA_FAILURE";

const GET_COUNTRIES_DATA_REQUEST = "GET_COUNTRIES_DATA_REQUEST";
const GET_COUNTRIES_DATA_SUCCESS = "GET_COUNTRIES_DATA_SUCCESS";
const GET_COUNTRIES_DATA_FAILURE = "GET_COUNTRIES_DATA_FAILURE";

const GET_LOOKINGFOR_DATA_REQUEST = "GET_LOOKINGFOR_DATA_REQUEST";
const GET_LOOKINGFOR_DATA_SUCCESS = "GET_LOOKINGFOR_DATA_SUCCESS";
const GET_LOOKINGFOR_DATA_FAILURE = "GET_LOOKINGFOR_DATA_FAILURE";

const GET_STATE_DATA_REQUEST = "GET_STATE_DATA_REQUEST";
const GET_STATE_DATA_SUCCESS = "GET_STATE_DATA_SUCCESS";
const GET_STATE_DATA_FAILURE = "GET_STATE_DATA_FAILURE";

const GET_CITY_DATA_REQUEST = "GET_CITY_DATA_REQUEST";
const GET_CITY_DATA_SUCCESS = "GET_CITY_DATA_SUCCESS";
const GET_CITY_DATA_FAILURE = "GET_CITY_DATA_FAILURE";

const SEND_OTP_DATA_REQUEST = "SEND_OTP_DATA_REQUEST";
const SEND_OTP_DATA_SUCCESS = "SEND_OTP_DATA_SUCCESS";
const SEND_OTP_DATA_FAILURE = "SEND_OTP_DATA_FAILURE";

const CHANGE_SEND_OTP_STATUS = "CHANGE_SEND_OTP_STATUS";

const CHANGE_VERIFY_OTP_TOCHECK = "CHANGE_VERIFY_OTP_TOCHECK";

const VERIFY_OTP_DATA_REQUEST = "VERIFY_OTP_DATA_REQUEST";
const VERIFY_OTP_DATA_SUCCESS = "VERIFY_OTP_DATA_SUCCESS";
const VERIFY_OTP_DATA_FAILURE = "VERIFY_OTP_DATA_FAILURE";

const REGISTER_DATA_REQUEST = "REGISTER_DATA_REQUEST";
const REGISTER_DATA_SUCCESS = "REGISTER_DATA_SUCCESS";
const REGISTER_DATA_FAILURE = "REGISTER_DATA_FAILURE";

const CLEAR_REGISTER_RESPONSE = "CLEAR_REGISTER_RESPONSE";

const SOCIALLOGIN_DATA_REQUEST = "SOCIALLOGIN_DATA_REQUEST";
const SOCIALLOGIN_DATA_SUCCESS = "SOCIALLOGIN_DATA_SUCCESS";
const SOCIALLOGIN_DATA_FAILURE = "SOCIALLOGIN_DATA_FAILURE";

const CLEAR_SOCIAL_LOGIN_RESPONSE = "CLEAR_SOCIAL_LOGIN_RESPONSE"

const SOCIAL_LOGIN_TYPE ="SOCIAL_LOGIN_TYPE"

export {
    MAIN_STEP_INPUT_CHANGE,
    VERIFY_CODE_INPUT,
    ABOUT_INFO_INPUT,
    ACCOUNT_INFO_INPUT,
    CHANGE_LOGIN_STEP,
    CHANGE_UPLOADIMAGE_INPUT,
    CHOOSE_LOCATION_INPUT,
    CHANGE_LOOKINGFOR_INPUT,
    GET_RELATIONSHIP_DATA_REQUEST,
    GET_RELATIONSHIP_DATA_SUCCESS,
    GET_RELATIONSHIP_DATA_FAILURE,
    GET_COUNTRIES_DATA_REQUEST,
    GET_COUNTRIES_DATA_SUCCESS,
    GET_COUNTRIES_DATA_FAILURE,
    GET_STATE_DATA_REQUEST,
    GET_STATE_DATA_SUCCESS,
    GET_STATE_DATA_FAILURE,
    GET_CITY_DATA_REQUEST,
    GET_CITY_DATA_SUCCESS,
    GET_CITY_DATA_FAILURE,
    SEND_OTP_DATA_REQUEST,
    SEND_OTP_DATA_SUCCESS,
    SEND_OTP_DATA_FAILURE,
    CHANGE_SEND_OTP_STATUS,
    CHANGE_VERIFY_OTP_TOCHECK,
    VERIFY_OTP_DATA_REQUEST,
    VERIFY_OTP_DATA_SUCCESS,
    VERIFY_OTP_DATA_FAILURE,
    REGISTER_DATA_REQUEST,
    REGISTER_DATA_SUCCESS,
    REGISTER_DATA_FAILURE,
    CLEAR_REGISTER_RESPONSE,
    GET_LOOKINGFOR_DATA_REQUEST,
    GET_LOOKINGFOR_DATA_SUCCESS,
    GET_LOOKINGFOR_DATA_FAILURE,
    SOCIALLOGIN_DATA_REQUEST,
    SOCIALLOGIN_DATA_SUCCESS,
    SOCIALLOGIN_DATA_FAILURE,
    CLEAR_SOCIAL_LOGIN_RESPONSE,
    SOCIAL_LOGIN_TYPE
}
